apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  annotations:
    info: "this is test deployment"
    email: "rajesh@fdf.com"
    owner: "rajesh"
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  replicas: 6
  selector:
    matchLabels:
      app: nginx-deployment

  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: kiran2361993/kubegame:v1
          name: nginx
        - image: kiran2361993/mydb:v1
          name: mysqldb
