apiVersion: v1
kind: Service
metadata:
  name: adapter-container-service
  labels:
    env: prod
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    env: prod
  type: NodePort
